name: rick_and_morty
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  http: ^1.1.0
  provider: ^6.0.5
  pretty_dio_logger: ^1.3.1
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  auto_route: ^7.7.0
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  rxdart: ^0.27.7
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  auto_route_generator: ^7.2.0


flutter:
  uses-material-design: true
